# pyproject.toml
[tool.ruff]
line-length = 88
select = [
    "ANN",
    "D", # Enable all pydocstyle (PEP 257) checks
    "E",
    "F",
    "W"
]
ignore = []
exclude = [
    "assasdb/data/",
    "assasdb/tools/jobs/",
    "test/dev_test/",
]
[tool.black]
line-length = 88
exclude = '''
/(
    assasdb/data/|
    assasdb/tools/jobs/|
)'''