name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"  # Match all branches
  pull_request:
    branches:
      - "**"  # Match all branches

jobs:
  
  lint:
    name: Run Ruff Linting
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the Docker container
      - name: Build Docker container for Ruff
        run: docker build -t assas-database-ruff .

      # Step 3: Run Ruff linting inside the Docker container
      - name: Run Ruff
        run: docker run --rm assas-database-ruff ruff check .

  test:
     name: Run Unit Tests
     runs-on: ubuntu-latest
      
     steps:
       # Step 1: Check out the code
       - name: Checkout code
         uses: actions/checkout@v3

       # Step 2: Build the Docker container
       - name: Build Docker container for tests
         run: docker build -t assas-database-test .
      
       # Step 3: Set up Python
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: 3.11  # Specify the Python version
      
       # Step 4: Install dependencies
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
      
       # Step 5: Change directory to `assas_database`
       - name: Install assas_database package
         run: |
          pip install -e .

       # Step 6: Run unit tests
       - name: Run tests
         env:
          PYTHONPATH: ${{ github.workspace }}/test:${{ env.PYTHONPATH }}
          ASTEC_ROOT: ${{ github.workspace }}
         run: |
          python test/test_astec_archive.py
          python test/test_database_handler.py
          python test/test_document_file.py
          python test/test_database_manager.py
          python test/test_conversion_handler.py
       
       - name: Upload HTML test report
         uses: actions/upload-artifact@v4
         with:
          name: html-test-report
          path: test_reports/

       - name: Upload test logs
         uses: actions/upload-artifact@v4
         with:
          name: test-logs
          path: test/logs/