name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests targeting the main branch

jobs:
  lint:
    name: Run Ruff Linting
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the Docker container
      - name: Build Docker container for Ruff
        run: docker build -t assas-database-ruff .

      # Step 3: Run Ruff linting inside the Docker container
      - name: Run Ruff
        run: docker run --rm assas-database-ruff ruff check .
